require File.expand_path(File.dirname(__FILE__) + "/scanny/issue")
require File.expand_path(File.dirname(__FILE__) + "/scanny/checks/check")
require File.expand_path(File.dirname(__FILE__) + "/scanny/checks/shell_expanding_methods_check")
require File.expand_path(File.dirname(__FILE__) + "/scanny/checks/backticks_check")
require File.expand_path(File.dirname(__FILE__) + "/scanny/checks/xss_check")
require File.expand_path(File.dirname(__FILE__) + "/scanny/runner")
